### ISSUE TITLE
DisplayRootViewFor doesn't invoke PrepareViewFirst

### ISSUE THREAD

**Issue by SGStino** [tibel/Caliburn.Light#47]
Wich means, no RootFrame gets set, and no INavigationService gets registered with the IoC container.

**Comment by tibel** [comment]
`DisplayRootViewFor()` is ViewModel-First  and `PrepareViewFirst()` is for View-First only.
For details see http://caliburnmicro.com/documentation/windows-runtime

**Comment by SGStino** [comment]
thanks, i just figured that out :(

**Comment by SGStino** [comment]
But if you use ViewModel First, the navigation service isn't available? How would one navigate to other pages with ViewModel First?
