### ISSUE TITLE
An instance method or closure cannot be used

### ISSUE THREAD

**Issue by belyansky** [tibel/Caliburn.Light#53]
After switching from VS 2013 to VS 2015 my WP app begins to throw exceptions during runtime.
Here is a simplified code sample:

```C#
public class FooViewModel
{
    private ICommand _barCommand;
    public ICommand BarCommand
    {
        get
        {
            if (_BarCommand == null)
            {
                _barCommand = DelegateCommand
                    .For(this)
                    .Execute(viewModel => viewModel.Bar())
                    .Build();
            }
            return _fooCommand;
        }
    }
        
    private void Bar()
    {
    }
}
```

`Execute` method from the code above throws `ArgumentException` with the message `An instance method or closure cannot be used` in process of command building.

How to avoid of this issue?

**Comment by belyansky** [comment]
Am I correct that the problem is related with #49?

**Comment by tibel** [comment]
Yes this is a duplicate. The new Roslyn compiler that is part of VS2015 changes how lambda expressions are compiled. Thus the checks for closures are not working any more.

I will try to fix this this week by removing these checks as a first step.
