### ISSUE TITLE
Version 2.1.0 and WP 8.1

### ISSUE THREAD

**Issue by belyansky** [tibel/Caliburn.Light#56]
Latest version of Caliburn.Light doesn't support WP 8.1 development. For example there is no `CaliburnApplication` and `INavigationService`. Is this correct?

**Comment by tibel** [comment]
I merged Win 10 support (#50) before the fixes Roslyn (#49).
Which included the remove of `win81` and `wpa81` projects in favor of `uap10`.

**Comment by belyansky** [comment]
So you're not planning to support `win81` and `wpa81` anymore. Am I right?

**Comment by tibel** [comment]
You are right.
But if you still need it, create a pull request and I will merge it.

**Comment by belyansky** [comment]
Ok. Thanks for clarifications.
